### ISSUE TITLE
Sync Rule ID Comparisons

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMConfigDocumenter#1]
On a Sync Rule Activity in a WF it shows the Sync Rule ID as a difference even when the Sync Rule DisplayNames are the same (it shows the Sync Rule DisplayName). When comparing to a previous config of the same instance the sync rule ID's would match but when comparing between Prod and Dev they wouldn't. So you should considering doing this comparison on DisplayName rather than the Sync rule ID

P.S. This is a great tool!

**Comment by NileshGhodekar** [comment]
I think this should happen only if there is some change to the linked sync rule (even though no change in the display name of the sync rules). If there are no changes at all in the corresponding sync rules, it should not get highlighted as a change in the WF. Can you please confirm?

PS: Change means it showing up in changes.xml file as changed object for any reason.

**Comment by NileshGhodekar** [comment]
There are changes on how dereferencing of guids is done so this is expected to be fixed in the latest release. Please try the new release.

**Comment by NileshGhodekar** [comment]
I believe the latest code check-in should fix this for good.
