### ISSUE TITLE
Ability to output data without compare

### ISSUE THREAD

**Issue by hartwc** [Microsoft/MIMConfigDocumenter#11]
Any chance of a version of this that outputs the existing configurations in the HTML format without having to compare to another version. Or is there a switch I can use for that result?

**Comment by NileshGhodekar** [comment]
Hi @hartwc, the only way to do this with one set of config files is to do it as mentioned in the usage instructions on homepage i.e. specify the same folder twice on the cmdline. Hope this answers your query, so I'll close this issue now.
