### ISSUE TITLE
Creation Times on MA's

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMConfigDocumenter#2]
Of course the MA I create in Dev and later import into Prod will have different Creation Times. You might want to ignore those in comparisons or give us the option to exclude those. The Modification Times would also be different

**Comment by henry-1** [comment]
I suggest to strip the part of domain components out of the DN of the container configuration of LDAP-style management agents like Active Directory MA before comparing them. If you compare DEV and PROD environment those parts will always be different.
Same is true for
- Forest Name
- Domain
- Last DC used

**Comment by NileshGhodekar** [comment]
The tool is "dumb" comparer and it will not decide which changes matter and which don't.  Neither will it know if you are doing fabrikam vs contoso or Prod Baseline 1 vs Prod Baseline 2. It is left to a human reader to ignore any unwanted changes highlighted.  If you assume Prod Baseline 1 vs Baseline2, some of these items won't showup as changes and other helps with troubleshooting or forensic investigation.

**Comment by DLundell** [comment]
I can see what you are saying. When comparing between Prod and Dev I probably want to see that the connection info is different to confirm the dev is writing to dev and prod to prod.

**Comment by NileshGhodekar** [comment]
I'm closing this request now as the tool will remain "dumb" file comparer for foreseeable future. And when an older version of this tool was being used internally for few  last years, I've not found anybody using any knobs - even when they were provided. People just choose to ignore what they don't want or reformat their documentation if something is not useful for their need.
