### ISSUE TITLE
False differences on export attribute flow

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMConfigDocumenter#3]
Here I have a duplicate export attribute flow one in a sync rule and one direct. But I have them in both environments and yet they both show up as different. So the sync rule flow from dev got compared to the direct flow in prod and the direct flow from dev got compared to the sync rule flow from prod

Data Source Attribute From Metaverse Attribute Mapping Type Allow Null Initial Flow Only 
mailNickname ←<red><crossed out> type mailNickname </crossed out></red>mailNickname <red><crossed out>Sync Rule - Expression</crossed out></red> Direct   

mailNickname ← <red><crossed out>mailNicknametype</crossed out><red>
mailNickname Direct <red><crossed out>Sync Rule - Expression</crossed out></red> Yes
[MIM Document Tool_error.docx](https://github.com/Microsoft/MIMConfigDocumenter/files/1027489/MIM.Document.Tool_error.docx)

**Comment by NileshGhodekar** [comment]
The tool is "dumb". These are processed in the order they are present in the config files. It does not make any intelligent decisions such as whether precedence matters or does not matter. That's left for a human reader to decide. BTW at least in this instance looks like FIM is dumb too, ideally it shouldn't allow this configuration, but I guess it expects people to know which one is going to win if both rules apply simultaneously.

**Comment by NileshGhodekar** [comment]
Closing this as previously commented.
