### ISSUE TITLE
Initial Flow only show up as allow nulls

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMConfigDocumenter#4]
I see flows on outbound sync rules with initial flow only and not allowing nulls instead showing up as allow nulls and not initial flow only
[MIM Document Tool_error.docx](https://github.com/Microsoft/MIMConfigDocumenter/files/1027492/MIM.Document.Tool_error.docx)

**Comment by DLundell** [comment]
I now think the tool isn't confusing the two but just getting the Allow Nulls wrong on sync rules -- it doesn't have that problem on direct flows but seems to say Yes on every single sync rule flow. This seems to occur in the MA Attribute Flow Section. In the Sync rule section it gets it right

**Comment by NileshGhodekar** [comment]
I'm not able to repro this. It's printing the correct values for Allow Null (as well as Initial Flows). Can you please provide more info / screenshots?
PS: for sync config the documenter uses "suppress_deletions" element and for service config it uses "allows-null" element. These two are Boolean inverse of each other but  are supposed to be kept in sync by the sync config logic where the actual processing happens. May be we are hitting some edge case?

**Comment by NileshGhodekar** [comment]
Closing for now as it seems the tool is reporting correctly.
