### ISSUE TITLE
MV Object Deletion rules

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMConfigDocumenter#5]
The report says that I have no MV Object deletion rules configured when I have 7 setup for declared-any and 1 for declared-last

**Comment by NileshGhodekar** [comment]
Thanks David! Please keep them coming! Really appreciated.

**Comment by DLundell** [comment]
Nilesh,

It is a great tool – even despite the flaws I am loving it and can’t wait for updates. Where has this tool been all my life?

David

**Comment by NileshGhodekar** [comment]
This is fixed in the latest release.
