### ISSUE TITLE
NullReferenceException in MIMConfigDocumenterCmd.exe

### ISSUE THREAD

**Issue by henry-1** [Microsoft/MIMConfigDocumenter#7]
Having a MIM WAL Powershell Activitiy without input and output paramters crashes the MIMConfigDocumenterCmd.exe.

GetReport'. Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at
MIMConfigDocumenter.MIMServicePolicyDocumenter.FillWorkflowActivityValueExpressions
(DataTable activityValueExpressionsTable, XElement hashtable, Int32 activityIndex, Int32 sectionIndex)
   at
MIMConfigDocumenter.MIMServicePolicyDocumenter.FillWorkflowActivityDetails
(Boolean pilotConfig)
   at MIMConfigDocumenter.MIMServicePolicyDocumenter.ProcessWorkflow()
   at MIMConfigDocumenter.MIMServicePolicyDocumenter.ProcessWorkflows()
   at MIMConfigDocumenter.MIMServicePolicyDocumenter.GetReport().
MIMConfigDocumenterLog Error: 40000 : MIMConfigDocumenter (1.17.0522.0):
05/30/2017 15:59:31.9009: Exception in 'MIMServiceConfigDocumenter :
GetReport'. Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at MIMConfigDocumenter.MIMServicePolicyDocumenter.GetReport()
   at
MIMConfigDocumenter.MIMServiceConfigDocumenter.ProcessServicePolicyConfiguration
()
   at MIMConfigDocumenter.MIMServiceConfigDocumenter.GetReport().

**Comment by NileshGhodekar** [comment]
Thanks! This will be fixed in the next release.

**Comment by NileshGhodekar** [comment]
Code checked in, so closing. Fix will go in the next release.

**Comment by NileshGhodekar** [comment]
The new release that fixes this and more is out now.
