### ISSUE TITLE
Sync engine attribute flow aggregated

### ISSUE THREAD

**Issue by elling** [Microsoft/MIMConfigDocumenter#9]
We have a setup with 14 separate import sync rules for Active Directory, all importing users with the same attribute flows (mostly), separated on OU filtering.

In the report, all the fields that are common between the 14 import sync rules appears 14 times PER rule, so I get 196 listings of AccountName, Email and so on.

Title is imported in 13 of the rules, and gives me 169 listings.. and so on and so on 👎 

The sync rules have inbound system scoping filter on DN. 

connectedSystemScope,"<scoping><scope><csAttribute>dn</csAttribute><csOperator>ENDSWITH</csOperator><csValue>OU=Users,OU=_DK,DC=testlab,DC=local</csValue></scope></scoping>",FIM Service,string,16.11.2015 12:34:22

**Comment by NileshGhodekar** [comment]
Thanks! We'll display the rule scope when documenting the attribute flows for sync engine. You'll still get as many rows though.

**Comment by NileshGhodekar** [comment]
Try the latest release v1.17.0610.0. Closing for now.
